# Generated by Django 4.0 on 2023-07-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_pictures/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='post_pictures/')),
                ('blight', models.BooleanField(default=False)),
                ('rust', models.BooleanField(default=False)),
                ('gray_leaf_spot', models.BooleanField(default=False)),
                ('healthy', models.BooleanField(default=False)),
                ('other', models.BooleanField(default=False)),
                ('date_posted', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
